version: 2.1

jobs:
  ubuntu18:
    docker: 
      name: ubuntu:18.04
    working_directory: ~/
    steps:
      - run: 
        name: Until we build a proper img
        command: |
          apt-get update; apt-get install -y git vim sudo python3 python3-pip build-essential
          update-alternatives --install /usr/bin/python python /usr/bin/python3 10
          update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10
          cd
          git clone https://github.com/bam241/install_scripts
          cd install_scripts/
          git checkout revamping
          rm ~/.bashrc
      - checkout
      - run:
          name: install pyne and its deps
          command: ./ubuntu18.04 dev
 
# Workflow part:
workflows:
  version: 2
  build:
    jobs:
      - ubuntu18