version: 2.1
jobs:
  ubuntu18:
    docker: 
      - image: ubuntu:18.04
    working_directory: ~/pyne
    steps:
      - run: apt-get update; 
      - run: apt-get install -y git vim sudo python3 python3-pip build-essential
      - run: update-alternatives --install /usr/bin/python python /usr/bin/python3 10
      - run: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10
      - run: rm ~/.bashrc
      - checkout
      - run:
          name: install pyne and its deps
          command: ./ubuntu_18.04 dev
 
# Workflow part:
workflows:
  version: 2
  build:
    jobs:
      - ubuntu18